/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ff7351",
        "outline-variant": "#484847",
        "primary-container": "#158b3f",
        "on-secondary-fixed-variant": "#006942",
        "surface-dim": "#0e0e0e",
        "on-tertiary-fixed-variant": "#005561",
        "inverse-primary": "#006e2f",
        "surface-variant": "#262626",
        "on-surface-variant": "#adaaaa",
        "on-primary": "#000000",
        "inverse-on-surface": "#565555",
        "on-secondary-fixed": "#00492c",
        "inverse-surface": "#fcf9f8",
        "secondary-dim": "#6beca9",
        "on-primary-container": "#002c0f",
        "on-error": "#450900",
        "tertiary-container": "#00e0fd",
        "tertiary-dim": "#00d1ec",
        "surface-container-high": "#201f1f",
        primary: "#1db954",
        background: "#0e0e0e",
        "surface-container": "#1a1919",
        "primary-fixed": "#1DB954",
        "on-primary-fixed-variant": "#006a2d",
        "secondary-fixed-dim": "#6beca9",
        surface: "#0e0e0e",
        outline: "#767575",
        "on-tertiary-container": "#004b56",
        "surface-bright": "#2c2c2c",
        "primary-fixed-dim": "#1DB954",
        "tertiary-fixed-dim": "#00d1ec",
        secondary: "#7afbb7",
        "surface-container-low": "#131313",
        "on-tertiary-fixed": "#00363e",
        "surface-container-lowest": "#000000",
        "secondary-container": "#006d44",
        "surface-container-highest": "#262626",
        "on-secondary": "#005e3a",
        "on-secondary-container": "#e1ffe9",
        "on-error-container": "#ffd2c8",
        "on-background": "#ffffff",
        "primary-dim": "#1DB954",
        "on-tertiary": "#005561",
        "error-container": "#b92902",
        "surface-tint": "#1DB954",
        "on-surface": "#ffffff",
        "secondary-fixed": "#7afbb7",
        "error-dim": "#d53d18",
        "on-primary-fixed": "#004a1d",
        tertiary: "#7de9ff",
        "tertiary-fixed": "#00e0fd",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};
